import { FilterName } from '@/types/effect';

export const filterTypes: FilterName[] = [
  'bad_TV',
  'black_And_White',
  'border_Double',
  'border_Simple',
  'blue_Print',
  'clarity',
  'color_Shift',
  'duotone',
  'high_Contrast',
  'negate',
  'oil_Painting',
  'pixelate',
  'posterize',
  'sepia',
  'tint',
  'vignette',
  'old_Vignette',
  'vintage',
  'retro_Palette',
  'ascii_Art',
  'sharpen',
  'emboss',
  'blur',
  'edge_Detection',
  'chromatic_Aberration',
  'bloom',
  'watercolor',
  'paint_on_canvas',
  'dithering',
];
