import * as THREE from 'three';

import type { OrbitControlsParams, ViewParams } from './types';

export const initialState = {
  camera: undefined,
  cameraType: 'perspective' as const,
  perspectiveCameraState: {
    position: new THREE.Vector3(0, 0, 15),
    rotation: new THREE.Euler(),
    target: new THREE.Vector3(),
    zoom: 1,
  },
  orthographicCameraState: {
    position: new THREE.Vector3(0, 0, 30),
    rotation: new THREE.Euler(),
    target: new THREE.Vector3(),
    zoom: 7,
  },
  viewMode: '2d' as const,
  materialCache: new Map(),
  isBlendUpdate: false,
  isUpdating: false,
  isGenerating: false,
  generationId: 0,
  currentGenerationId: 0,
  meshes: [],
  lightingParams: {
    ambient: {
      intensity: 1.0,
    },
    directional: {
      position: [5, 5, 5] as [number, number, number],
      intensity: 0.8,
    },
  },
  perspectiveControls: {
    enableDamping: true,
    dampingFactor: 0.05,
    rotateSpeed: 0.8,
    zoomSpeed: 0.8,
    panSpeed: 0.8,
    minDistance: 3.33,
    maxDistance: 20,
    target: [0, 0, 0] as [number, number, number],
  },
  orthographicControls: {
    enableDamping: true,
    dampingFactor: 0.05,
    rotateSpeed: 0.6,
    zoomSpeed: 0.5,
    panSpeed: 0.6,
    minDistance: 3.33,
    maxDistance: 20,
    target: [0, 0, 0] as [number, number, number],
  },
  geometryParams: {
    defaultWidth: 5,
    colorSpace: THREE.SRGBColorSpace,
  },
  textureCache: new Map(),
  geometryCache: new Map(),
  perspectiveParams: {
    layerSpacing: 0.2,
    layerThickness: 0.05,
    zoom: 1,
  },
  orthographicParams: {
    layerSpacing: 0.2,
    layerThickness: 0.05,
    zoom: 1,
  },
  needsUpdate: false,
  updateQueue: new Set<string>(),
  batchUpdate: false,
  meshCache: {},
  framesByLayer: {},
  textureManager: {
    cache: {},
    addTexture: () => {},
    getTexture: () => null,
    cleanup: () => {},
    clear: () => {},
  },
  frameInterval: 1000 / 24,
  lastFrameTime: 0,
  fps: 24,
  projectId: null,
  spritesheetLayout: null,
  maxFrames: 0,
  currentFrame: 0,
  updateMeshPositions: () => {},
  updateMeshThickness: () => {},
  clearGeometryCache: () => {},
  clearTextureCache: () => {},
  setOrbitControls: () => {},
  setGeometryParams: () => {},
  setViewMode: () => {},
  triggerGeneration: async () => {},
  clearCache: () => {},
  setMeshes: () => {},
  setIsGenerating: () => {},
  createMesh: async () => {
    await Promise.resolve();
    return new THREE.Mesh();
  },
  updateMeshTextures: () => {},
  cleanupMesh: () => {},
  setCameraType: () => {},
  setPerspectiveCameraState: () => {},
  setOrthographicCameraState: () => {},
  setPerspectiveControls: () => {},
  setOrthographicControls: () => {},
  setLayerSpacing: () => {},
  setLayerThickness: () => {},
  getCurrentControls: () => ({}) as OrbitControlsParams,
  getCurrentParams: () => ({}) as ViewParams,
  setCurrentControls: () => {},
  resetToFlatView: () => {},
  handleMeshUpdate: () => {},
  handleCameraSave: () => {},
  handleCameraRestore: () => {},
  cleanupMeshesFromScene: () => {},
  setZoom: () => {},
  updateCamera: () => {},
  setCamera: () => {},
  setActiveControls: () => {},
  setDimensions: () => {},
  setPerspectiveParams: () => {},
  setOrthographicParams: () => {},
  validateMeshes: () => false,
  updateDimensions: () => {},
  startAnimation: () => {},
  stopAnimation: () => {},
  loadAnimatedImages: async () => {},
  loadBlendedFrames: async () => {
    await Promise.resolve();
    return { element: new Image(), frames: [] };
  },
  setFPS: () => {},
  setCurrentFrame: () => {},
  animationState: {
    isPaused: false,
    lastFrame: 0,
    lastFrameTime: 0,
    wasPlaying: true,
    animationFrameId: undefined,
  },
  setAnimationState: () => {},
};
