export const CONTROL_CONFIGS = [
  {
    key: 'scanlineIntensity',
    label: 'Scanlines',
    defaultValue: 5.0,
    min: 0.0,
    max: 15.0,
    step: 0.5,
    color: 'rgb(var(--color-secondary))',
  },
  {
    key: 'glitchFrequency',
    label: 'Glitch',
    defaultValue: 1.0,
    min: 0.0,
    max: 5.0,
    step: 0.1,
    color: 'rgb(var(--color-secondary))',
  },
  {
    key: 'jitterStrength',
    label: 'Jitter',
    defaultValue: 3.0,
    min: 0.0,
    max: 10.0,
    step: 0.5,
    color: 'rgb(var(--color-secondary))',
  },
  {
    key: 'colorShiftStrength',
    label: 'Color Shift',
    defaultValue: 10.0,
    min: 0.0,
    max: 25.0,
    step: 0.5,
    color: 'rgb(var(--color-secondary))',
  },
  {
    key: 'distortionStrength',
    label: 'Distortion',
    defaultValue: 4.0,
    min: 0.0,
    max: 15.0,
    step: 0.5,
    color: 'rgb(var(--color-secondary))',
  },
  {
    key: 'rollSpeed',
    label: 'Roll Speed',
    defaultValue: 2.0,
    min: 0.0,
    max: 10.0,
    step: 0.5,
    color: 'rgb(var(--color-secondary))',
  },
  {
    key: 'frameJumpIntensity',
    label: 'Frame Jumps',
    defaultValue: 0.0,
    min: 0.0,
    max: 100.0,
    step: 1.0,
    color: 'rgb(var(--color-secondary))',
  },
] as const;
